services:
  frontend-papse:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: frontend-papse
    restart: always
    networks:
      - papse_network

networks:
  papse_network:
    external: true
