services:
  app:
    container_name: api-papse
    build: .
    env_file:
      - .env
    dns:
      - 8.8.8.8
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - papse_network
  db:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - .env
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - papse_network
networks:
  papse_network:
    external: true
volumes:
  mysql-data:
